name: lmodroid build for oxygen

on:
  workflow_dispatch:
jobs:
  test:
    name: Build LMODROID for oxygen using foss.crave.io

    runs-on: self-hosted

    steps:
    - name: Create workspace
      run: mkdir lmo
    - name: Enter Workspace
      run: cd lmo
      continue-on-error: true
    - name: Run Script
      run: curl -sf https://raw.githubusercontent.com/sounddrill31/android_build_scripts/lmodroid-oxygen/build.sh | sh
      continue-on-error: true
    - name: Go back to old workspace
      run: cd ..
