name: plros build for oxygen

on:
  workflow_dispatch:
jobs:
  test:
    name: Build plros for oxygen using foss.crave.io

    runs-on: self-hosted

    steps:
    - name: Create workspace
      run: mkdir plros
      continue-on-error: true

    - name: Enter Workspace
      run: cd plros
      continue-on-error: true
    - name: Install gh command
      run: curl -sS https://webi.sh/gh | sh
    - name: Cleanup
      run: rm -rf oxygen/
    - name: Exports
      run: |
        export BUILD_HOSTNAME=crave; \
        export BUILD_USERNAME=sounddrill31
    - name: Run Script
      run: curl -sf https://raw.githubusercontent.com/sounddrill31/android_build_scripts/plrOS-oxygen/build-exp.sh | sh
    - name: Find output file
      run: |
        filepath=$(find ./oxygen -type f -name '*-oxygen.zip'); \
        export filename=$(basename "$filepath"); \
        echo $filename
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: | 
          oxygen/recovery.img
          oxygen/boot.img
          oxygen/vendor_boot.img
          oxygen/vendor.img
          oxygen/system.img
          oxygen/*.zip
        name: ${{ github.event.inputs.MAKEFILE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Target: ${{ github.event.inputs.MAKEFILE_NAME }}-${{ github.event.inputs.BUILD_TYPE }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
