name: plros build for oxygen

on:
  workflow_dispatch:
jobs:
  test:
    name: Build plros for oxygen using foss.crave.io

    runs-on: self-hosted

    steps:
    - name: Create workspace
      run: mkdir lmo
      continue-on-error: true

    - name: Enter Workspace
      run: cd lmo
      continue-on-error: true
    - name: Cleanup
      run: rm -rf oxygen/
    - name: Run Script
      run: curl -sf https://raw.githubusercontent.com/sounddrill31/android_build_scripts/plrOS-oxygen/build.sh | sh
      continue-on-error: true
    - name: Find output file
      run: |
        filepath=$(find ./oxygen -type f -name '*-oxygen.zip'); \
        export filename=$(basename "$filepath"); \
    - name: Parse Filename
      run: |
        name="${filename%.zip}"; \
        rom_name="${filename%%-*}"; \
        export build_date=$(echo "$filename" | grep -oP '\b\d{8}\b'); \
        device=${name##*-}; \
        export tagname="${rom_name}-${device}-${build_date}"
        echo $tagname
    - name: Create and upload Release
      run: |
        gh release create ${tagname} ${device}/${filename} ${device}/recovery.img -R https://github.com/sounddrill31/releases --prerelease -t "${filename}" -n "testing"
    - name: Update OTAs
      run: |
        git clone https://github.com/sounddrill31/Releases; \
        json_file="Releases/plros-oxygen.json"; \
        sed -i -E "s/\"datetime\":[[:space:]]+([0-9]+)/\"datetime\": $build_date/" "$json_file"; \
        sed -i -E "s/(\"filename\":[[:space:]]*)\".*\"/\1\"$filename\"/" "$json_file"; \
        # will do size later \
        sed -i -E "s/(.*)(.zip)/\1${filename}.zip/g" "$json_file"; \
        sed -i -E "s|([^/]*)/[^/]*\"|\1/$filename\"|" "$json_file"; \
        package_hash=$(sha256sum "${device}/${filename}" | awk '{ print $1 }'); \
        sed -i -E "s/\"id\":[[:space:]]*\"[^\"]+\"/\"id\": \"$package_hash\"/" "$json_file"; \
        
